settings:
  title: 'Status Page'
  url: 'https://status.uua.app' # used for Slack messages
  logo: logo-want-want.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Object Storage Service # unique identifier
    name: R2 Storage
    description: 'Cloudflare R2 Storage' # default=empty
    url: 'https://cdn.jghg.eu.org/img/mosaic.jpeg' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

#  - id: Blog
#    name: Blog
#    description: 'Welcome to microfeed, a lightweight content management system (CMS) self-hosted on Cloudflare.'
#    url: 'https://eveo.eu.org/'
#    method: GET
#    expectStatus: 200

  - id: Image-Hosting
    name: Image-Hosting
    description: 'Based on Telegraph and Cloudflare Pages'
    url: 'https://pic.jghg.eu.org'
    method: GET
    expectStatus: 200

  - id: ChatGPT-Next-Web
    name: ChatGPT-Next-Web
    description: 'You can use your own OpenAI API Key.'
    url: 'https://gpt.jghg.eu.org'
    method: GET
    expectStatus: 200

  - id: Bing Chat Server
    name: Sydney
    description: 'Chat with Sydney with _U Cookie. https://github.com/adams549659584/go-proxy-bingai#设置用户'
    url: 'https://newbing.jghg.eu.org'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false

  - id: OpenAI Bill Check
    name: OpenAI-Bill-Check
    description: 'Check OpenAI Usage by API Key.'
    url: 'https://openai-bill.jghg.eu.org'
    method: GET
    expectStatus: 200

  - id: GitHub Proxy
    name: GitHub-Proxy
    description: 'GitHub Reverse-proxy.'
    url: 'https://gh.jghg.eu.org/https://raw.githubusercontent.com/torvalds/linux/master/README'
    method: GET
    expectStatus: 200

  - id: URL Shortener
    name: URL-Shortener
    description: 'Easy URL shortener service. Attention! Short links created by visitors are valid only for a few minutes.'
    url: 'https://rzr.me'
    method: GET
    expectStatus: 200

  - id: IP Config
    name: IP-Config
    description: 'Check your IP (nothing else)'
    url: 'https://ip.jghg.eu.org'
    method: GET
    expectStatus: 200
